title: "Gregory Sale"
author: "Gregory Sale"
description: "Cambridge, UK"
permalink: /:year/:month/:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header
show_title: true          # always keep the site title visible


# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Blog"}
  - {file: "README.md", title: "About me"}
  
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "gregory2996@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/gregory-sale"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/gregory-sale/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
